### PR TITLE
Fixed type-hint

### PR DESCRIPTION
**Pull request by holtkamp**

### CODE REVIEW

**Comment by mnapoli** [comment]
:+1:

**Comment by holtkamp** [comment]
you're fast ;)

**Comment by holtkamp** [comment]
Mm, maybe even too fast... The BaseClass is abstract and can therefore not be instantiated. When looking at the DataProvider function, fetching the entry identified with the BaseClass, WOULD return a SubClass. Sorry... Confused by the naming...

**Comment by mnapoli** [comment]
Haha no problem that's my mistake, given that was a comment in a test it wasn't a big deal so I just pushed merge, I'll revert it ;)

**Pull request merged**
