### PR TITLE
Make autowiring and annotations work for `DI\object()` inside arrays

### PR DESCRIPTION
**Pull request by leonbobster**
quick fix for #343

### CODE REVIEW

**Comment by mnapoli** [comment]
Thanks for the pull request, however it seems the build failed and that no tests are covering the new behavior. Also this is adding specific behavior where it could be made more generic (i.e. not having custom behavior for `ArrayDefinition` in `SourceChain` - maybe by doing what's described in https://github.com/PHP-DI/PHP-DI/issues/343#issuecomment-195239192).

**Comment by leonbobster** [comment]
FYI: I'm not sure the build failed because of those changes. I have the same 4 fails in tests without my fix.

**Comment by leonbobster** [comment]
Do you mean It should be implemented using existing HasSubDefinition? It looks like by the nature this interface implies singular relation. Should it be extended with special methods or implemented special interface for multiple Sub-definitions? Or in some other way ... ?

**Comment by mnapoli** [comment]
Actually I think I was wrong, `HasSubDefinition` is for definitions that extend another one (now I realize the naming of that interface is maybe not perfect). So this pull request is maybe a good solution, I'll have a deeper look. The big thing missing are tests though.

I had a look at the build fail and I think it's just a matter of rebasing your pull request against master.

**Comment by leonbobster** [comment]
I'll add tests

**Comment by mnapoli** [comment]
Thanks for the pull request, closing per https://github.com/PHP-DI/PHP-DI/issues/343#issuecomment-306035969

**Pull request closed without merging**
