### PR TITLE
Fixes FactoryResolver#resolve ignoring passed parameters

### PR DESCRIPTION
**Pull request by Aijoona**
FactoryResolver#resolve seems to be ignoring the passed arguments.

### CODE REVIEW

**Comment by mnapoli** [comment]
Thanks, I'm not sure I understand the problem. Are you able to add an integration test? That should help to understand.

**Comment by holtkamp** [comment]
Maybe relats to https://github.com/PHP-DI/PHP-DI/issues/651 ?

**Comment by Aijoona** [comment]
For more context.

Somewhere in my code, I got something like this (a glorified cURL wrapper):
```PHP

    /**
     * @param $resource
     * @param array $payload
     * @param array $options
     * @return mixed
     */
    public function get($resource, array $payload = [], array $options = [])
    {
        return $this->factory
            ->make(Get::class, [
                'resource' => $resource,
                'payload' => $payload,
                'options' => $options
            ])
            ->exec();
    }
```

In my integration tests I need to fake the cURL call, so I added a new definition for the Get::class that overrides the cURL request  (the Client class just forwards the definitions to the container builder).
```PHP

    protected function getClientWithFixedGetResponse($httpCode, $response)
    {
        return new Client(null, null, [
            'definitions' => [
                Get::class => function ($resource, $payload = [], $options = []) use ($httpCode, $response) {
                    $handler = new FixedResponseGetRequest($resource);
                    $handler->setCallback(function () use ($response, $httpCode) {
                        return [$httpCode, $response];
                    });

                    return $handler;
                }
            ]
        ]);
    }

```
Now, the current implementation ignores all the parameters passed in the make call (in this case {resource, payload, options}), so the FactoryResolver just passes the "default params": {container, definition}.

In my code this means an exception being thrown because obviously the container is not the url string expected.

**Comment by mnapoli** [comment]
Thank you!

**Pull request merged**
