### PR TITLE
Adds return values to docblock

### PR DESCRIPTION
**Pull request by bjoern-tantau**
Adds the return values of the functions to the docblock to aid IDEs.

### CODE REVIEW

**Comment by mnapoli** [comment]
These docblocks are duplicating information which is already in the code (the return types). I don't think this helps IDEs at all since the information is already there.

**Comment by bjoern-tantau** [comment]
Ah, you're right. My IDE (Netbeans) wasn't showing any autocompletion for these method's return-values and I thought it was because of the missing docblocks, but I guess it must be some bug with Netbeans, as it doesn't even work with the docblock, but on other functions. Maybe because of the namespace.

**Comment by mnapoli** [comment]
Good to know, thanks for the follow up and sorry :)

**Comment by bjoern-tantau** [comment]
For anyone with the same problem, I opened a bug report for Netbeans at https://issues.apache.org/jira/browse/NETBEANS-1859

**Pull request closed without merging**
