### PR TITLE
support variadic parameter on addDefinitions

### PR DESCRIPTION
**Pull request by juliangut**
As per this comments: https://github.com/PHP-DI/PHP-DI/issues/618#issuecomment-416686620 https://github.com/PHP-DI/PHP-DI/issues/618#issuecomment-416954644

Support variadic arguments when calling addDefinitions

### CODE REVIEW

**Comment by juliangut** [comment]
The build error is coming from PHPStan

```
------ ------------------------------------------------------------------
 Line src/ContainerBuilder.php
 ------ ------------------------------------------------------------------
  314    PHPDoc tag @param for parameter $definitions with type
array<array|DI\Definition\Source\DefinitionSource|string> is not
subtype of native type array<int, mixed>
 ------ ------------------------------------------------------------------
```

This is the code

```php
    /**
     * Add definitions to the container.
     *
     * @param string[]|array[]|DefinitionSource[] $definitions Can be an array of definitions, the
     *                                                   name of a file containing definitions
     *                                                   or a DefinitionSource object.
     * @return $this
     */
    public function addDefinitions(...$definitions) : self
    {
    [...]
```

**Comment by mnapoli** [comment]
Regarding the coding style I've added a commit on master to fix the coding style (Symfony added a new rule that breaks BC): a9892481aec265b83591a444f1a33ceaf6b44cfb If you merge/rebase master your PR should be OK.

As for phpstan I think you don't need to update the types in the phpdoc, try this and see if it works:

```
string|array|DefinitionSource
```

**Comment by juliangut** [comment]
Finally! dockblock syntax on variadic arguments does not seam to be well documented

https://github.com/phpstan/phpstan/issues/979#issuecomment-386222212

**Comment by mnapoli** [comment]
Thanks!

**Pull request merged**
