### PR TITLE
added use statement to zf1 bridge docs

### PR DESCRIPTION
**Pull request by Anyqax**

### CODE REVIEW

**Comment by mnapoli** [comment]
Hi, thanks for the pull request but importing the annotation is not necessary, it works without the `use` statement.

**Comment by Anyqax** [comment]
You´re right... a PHPStorm inspection complained about the missing import. That´s why I tried the namespaced annotation `@DI\Annotation\Injectable()`... which didn´t work, so I added the use statement.

**Comment by mnapoli** [comment]
Right, PhpStorm will complain. However it's not mandatory, Doctrine has an option to allow the annotation not namespaced. The choice is yours :)

**Comment by mnapoli** [comment]
(and regarding the docs I think it's better to keep them as simple as possible)

**Pull request closed without merging**
