### PR TITLE
Fix make() fails when using decorate

### LINKED ISSUE #554: make() fails when using decorate
Hi @mnapoli 

I am getting currently this error with PHP-DI 5.4.5:

```
Entry "Piwik\Plugins\CoreHome\FooBar" cannot be resolved: Parameter $customer of __construct() has no value defined or guessableFull definition:Object ( class = Piwik\Plugins\CoreHome\FooBar scope = singleton lazy = false __construct( $customer = #UNDEFINED# ))
```

when calling:
```php
            return $container->make('Piwik\Plugins\CoreHome\FooBar', array(
                'customer' => $customer
            ));
```

and having a DI config like:

```php
'Piwik\Plugins\CoreHome\FooBar' => DI\decorate(function ($customer, \Interop\Container\ContainerInterface $c) {

        $myTest = $c->get('test.vars.myTest');
        if (!empty($myTest)) {
            return new MyTest();
        }

        return $customer;
    }),
```

The class looks like this:
```
class FooBar {
    /**
     * @var array
     */
    private $customer;

    public function __construct($customer)
    {
        $this->customer = $customer;
    }
```

It works nicely as soon as I remove the `DI\decorate()` but not when I add it. It does not even go into the decorator when debugging it.

It fails in `ObjectCreator::createInstance()` with a `DefinitionException`.

It seems like the passed parameters get lost in `DecoratorResolver::resolve(Definition $definition, array $parameters = [])` where the $parameters are actually never used.

### PR DESCRIPTION
**Pull request by tsteur**
fixes #554

@mnapoli looks like this might fix the issue

### CODE REVIEW

**Comment by mnapoli** [comment]
Thanks, would you have time to add tests? (https://github.com/PHP-DI/PHP-DI/blob/5.4/tests/UnitTest/ContainerMakeTest.php might be a good place in this branch) Sorry I did not check that earlier.

**Comment by tsteur** [comment]
I tried to write a test but failed.

In https://github.com/PHP-DI/PHP-DI/blob/5.4/tests/UnitTest/ContainerMakeTest.php I couldn't figure out on how to add a decorator to the already built dev container. Then wanted to add a test to https://github.com/PHP-DI/PHP-DI/blob/5.4/tests/UnitTest/Definition/Resolver/DecoratorResolverTest.php
like this:

```php


    /**
     * @test
     */
    public function should_resolve_parameters()
    {
        $previousDefinition = new ObjectDefinition(PassByReferenceDependency::class);

        $callable = function ($previous, ContainerInterface $container) {
            return $previous->foo .= 'baz';
        };
        $definition = new DecoratorDefinition(PassByReferenceDependency::class, $callable);
        $definition->setSubDefinition($previousDefinition);

        $stdClass = new stdClass();
        $object = $this->resolver->resolve($definition, array('object' => $stdClass));
        $this->assertEquals('barbaz', $object->foo);
    }
```

But there are too many classes involved and I can't make it work :) No clue on how those definitions should be composed etc.

**Comment by mnapoli** [comment]
I tried to push a commit to this branch but I am not allowed, here is the test I wrote:

```php
    /**
     * @see https://github.com/PHP-DI/PHP-DI/issues/554
     */
    public function testMakeWithDecorator()
    {
        $builder = new ContainerBuilder;
        $builder->addDefinitions([
            Foo::class => \DI\decorate(function ($previous) {
                return $previous;
            }),
        ]);
        $container = $builder->build();
        $result = $container->make(Foo::class, [
            'bar' => 'baz',
        ]);
        $this->assertEquals('baz', $result->bar);
    }
```

With this fixture class:

```php
namespace DI\Test\UnitTest\Fixtures;

class Foo
{
    public $bar;

    public function __construct($bar)
    {
        $this->bar = $bar;
    }
}
```

Let me know if that sounds like your problem (it does fail on 5.4).

**Comment by tsteur** [comment]
Pushed the test 👍  Thanks a lot. Edits should be allowed btw.

**Comment by mnapoli** [comment]
Thanks!

**Pull request merged**
